language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.m2"

script: "mvn clean package"

notifications:
  email:
    recipients:
      - kihong.kwon7389@gmail.com
    on_success: always
    on_failure: always