language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.m2"

script: "mvn clean package"

before_deploy:
  - zip -r aws-refapp *
  - mkdir -p deploy
  - mv aws-refapp.zip deploy/aws-refapp.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: "net.kkh-study.aws-refapp"
    region: ap-northeast-1
    skip_cleanup: true
    acl: public_read
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: kihong-kwon/aws-refapp
      branch: master

notifications:
  email:
    recipients:
      - kihong.kwon7389@gmail.com
    on_success: always
    on_failure: always
